# DBScann #

In [ ]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
import numpy as np

X, y = make_moons(n_samples=1000, noise=0.05)
dbscan = DBSCAN(eps=0.05, min_samples=5)
dbscan.fit(X)
dbscan.labels_

In [11]:
len(dbscan.core_sample_indices_) # indeces of core samples

801

In [12]:
dbscan.components_ # array of core instances

array([[ 1.88888352,  0.00557067],
       [ 0.83739011, -0.50077983],
       [ 0.16190466, -0.14148709],
       ...,
       [ 0.05781877,  0.33043963],
       [-1.0035676 ,  0.17143454],
       [-0.90119879,  0.45734103]])

In [13]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [14]:
X_new = np.array([[-0.5, 0], [0,0.5], [1, -0.1], [2,1]])
knn.predict(X_new)

array([7, 2, 3, 0], dtype=int64)

In [15]:
knn.predict_proba(X_new)

array([[0.  , 0.  , 0.14, 0.  , 0.  , 0.  , 0.  , 0.86, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.04, 0.  , 0.6 , 0.  , 0.32, 0.  , 0.  , 0.  , 0.02, 0.02],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [29]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)
# y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx] # to first choose only the labels of the core_samples does not make sense to me...
y_pred = dbscan.labels_[y_pred_idx]
y_pred[y_dist > 0.2] = -1
y_pred.ravel()

array([-1,  5,  0, -1], dtype=int64)